[package]
name = "py-interop-score"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "interop_score"
crate-type = ["cdylib"]

[dependencies]
interop-score = { path = "../core" }
pyo3 = "0.18.3"
