name: Update interop-scores
on:
  push:
    branches:
      - main
  # Trigger every three hours, or manually.
  schedule:
    - cron: '20 */3 * * *'
  workflow_dispatch:
jobs:
  update-gh-pages:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: repos
        key: cache-repos

    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: "Update Interop scores"
      run: "./ci/update-scores.sh"
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
